project_name: backbomb

before:
  hooks:
  - go mod download

builds:
  -
    main: .
    binary: backbomb
    goos:
      - windows
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 6
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: desc
  filters:
    exclude:
    - '^MERGE'
    - "{{ .Tag }}"

release:
  github:
    owner: hahwul
    name: backbomb

brews:
  -
    name: backbomb
    tap:
      owner: hahwul
      name: homebrew-backbomb
    url_template: "https://github.com/hahwul/backbomb/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: hahwul
      email: hahwul@gmail.com
    folder: Formula
    homepage: "https://www.hahwul.com"
    description: "Dockerized penetration-testing/bugbounty/app-sec testing environment"
    test: |
      system "#{bin}/backbomb version"
    install: |
      bin.install "backbomb"
snapcrafts:
  -
    name: backbomb
    # Remember you need to `snapcraft login` first.
    publish: true
    summary: Dockerized penetration-testing/bugbounty/app-sec testing environment
    description: Dockerized penetration-testing/bugbounty/app-sec testing environment
    grade: stable
    confinement: strict
    license: MIT

    apps:
      backbomb:
        plugs: ["home","network","network-bind"]
